# Generated by Django 4.0 on 2021-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_name', models.CharField(max_length=100)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
