# Generated by Django 4.0 on 2021-12-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lift',
            name='time',
        ),
    ]
