# Generated by Django 4.0 on 2021-12-08 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0004_nutrition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 8)),
        ),
    ]
