# Generated by Django 4.0 on 2021-12-08 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0005_alter_nutrition_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('date', models.DateField(default=datetime.date(2021, 12, 8))),
            ],
        ),
    ]
