# Generated by Django 4.0 on 2021-12-09 12:29

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0006_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='reps',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lift',
            name='sets',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lift',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='calories',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='carbohydrates',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 9, 12, 29, 39, 261641, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 9, 12, 29, 39, 261641, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
