# Generated by Django 4.0 on 2021-12-09 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0007_alter_lift_reps_alter_lift_sets_alter_lift_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 9)),
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 9)),
        ),
    ]
